<x-layouts.app title="Evraklarım">
    <div><p class="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-600">Belge Yönetimi</p><h1 class="mt-1 text-3xl font-bold text-slate-950">{{ request('document_type') === 'petition' ? 'Dilekçeler' : 'Evraklarım' }}</h1><p class="mt-1 text-sm text-slate-500">Erişebildiğiniz hukuki dosyalardaki özel ve sürümlü evraklar.</p></div>
    <form class="mt-6 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-6" method="GET" action="{{ route('legal-documents.index') }}"><input name="search" value="{{ request('search') }}" placeholder="Başlık, dosya adı veya dosya no" class="rounded-lg border-slate-300 xl:col-span-2"><select name="case_file" class="rounded-lg border-slate-300"><option value="">Tüm hukuki dosyalar</option>@foreach($caseFiles as $caseFile)<option value="{{ $caseFile->id }}" @selected((string) request('case_file') === (string) $caseFile->id)>{{ $caseFile->case_no }}</option>@endforeach</select><select name="folder" class="rounded-lg border-slate-300"><option value="">Tüm klasörler</option>@foreach($folders as $folder)<option value="{{ $folder->id }}" @selected((string) request('folder') === (string) $folder->id)>{{ $folder->name }}</option>@endforeach</select><select name="document_type" class="rounded-lg border-slate-300"><option value="">Tüm evrak türleri</option><option value="petition" @selected(request('document_type') === 'petition')>Dilekçe</option><option value="evidence" @selected(request('document_type') === 'evidence')>Delil</option><option value="notice" @selected(request('document_type') === 'notice')>Tebligat</option><option value="report" @selected(request('document_type') === 'report')>Rapor</option><option value="contract" @selected(request('document_type') === 'contract')>Sözleşme</option><option value="invoice" @selected(request('document_type') === 'invoice')>Fatura</option><option value="enforcement" @selected(request('document_type') === 'enforcement')>İcra Evrakı</option><option value="other" @selected(request('document_type') === 'other')>Diğer</option></select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filtrele</button></form>
    <div class="mt-6 space-y-3">
        @forelse($documents as $document)
            <article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="font-mono text-xs font-semibold text-indigo-600">{{ $document->caseFile->case_no }}</span><span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{{ $document->folder?->name ?? 'Klasörsüz' }}</span></div><h2 class="mt-2 break-words font-semibold text-slate-950">{{ $document->title ?: $document->original_name }}</h2><p class="mt-1 text-xs text-slate-500">{{ $document->original_name }} · {{ $document->human_size }} · v{{ $document->currentVersion?->version_no ?? 1 }}</p></div><div class="flex gap-2">@if($document->currentVersion && in_array($document->currentVersion->mime_type, ['application/pdf', 'image/jpeg', 'image/png'], true))<a class="rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700" target="_blank" href="{{ route('document-versions.preview', $document->currentVersion) }}">Önizle</a>@endif<a class="rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white" href="{{ route('documents.download', $document) }}">İndir</a></div></div>
                @if($document->currentVersion)<details class="mt-4 border-t border-slate-100 pt-3"><summary class="cursor-pointer text-xs font-medium text-slate-600">Sürüm geçmişini göster</summary><div class="mt-3 space-y-2">@foreach($document->versions->sortByDesc('version_no') as $version)<div class="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-xs"><span><strong>v{{ $version->version_no }}</strong> · {{ $version->uploader->name }} · {{ $version->created_at->format('d.m.Y H:i') }} @if($version->change_note)· {{ $version->change_note }}@endif</span><div class="flex gap-2">@if(in_array($version->mime_type, ['application/pdf', 'image/jpeg', 'image/png'], true))<a class="text-indigo-600" target="_blank" href="{{ route('document-versions.preview', $version) }}">Önizle</a>@endif<a class="text-slate-700" href="{{ route('document-versions.download', $version) }}">İndir</a></div></div>@endforeach</div></details>@endif
            </article>
        @empty
            <div class="rounded-xl border border-dashed border-slate-300 p-14 text-center text-sm text-slate-500">Filtrelere uygun evrak bulunamadı.</div>
        @endforelse
    </div>
    @if($documents->hasPages())<div class="mt-6">{{ $documents->links() }}</div>@endif
</x-layouts.app>
