<?php

use App\Http\Controllers\Admin\CaseTypeController as AdminCaseTypeController;
use App\Http\Controllers\Admin\EventTypeController as AdminEventTypeController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\AdvancedSearchController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\AuthenticatedSessionController;
use App\Http\Controllers\CaseAssignmentRequestController;
use App\Http\Controllers\CaseFileAssignmentController;
use App\Http\Controllers\CaseFileController;
use App\Http\Controllers\CaseFileDocumentController;
use App\Http\Controllers\CaseFilePartyController;
use App\Http\Controllers\CaseFileStatusController;
use App\Http\Controllers\CaseFinancialEntryController;
use App\Http\Controllers\ClientCommunicationController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeadlineController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\DocumentFolderController;
use App\Http\Controllers\DocumentVersionController;
use App\Http\Controllers\EventCaseFileController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\EventUpdateController;
use App\Http\Controllers\HearingController;
use App\Http\Controllers\LegalCalendarController;
use App\Http\Controllers\LegalDocumentController;
use App\Http\Controllers\LegalTaskController;
use App\Http\Controllers\MediationController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\NewPasswordController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PasswordResetLinkController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SecurityController;
use App\Http\Controllers\ServiceNoticeController;
use App\Http\Controllers\TwoFactorChallengeController;
use App\Http\Controllers\UdfDocumentController;
use App\Http\Controllers\UyapImportController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:6,1')->name('login.store');
    Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])->middleware('throttle:password-reset')->name('password.email');
    Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.update');
    Route::get('/two-factor-challenge', [TwoFactorChallengeController::class, 'create'])->name('two-factor.challenge');
    Route::post('/two-factor-challenge', [TwoFactorChallengeController::class, 'store'])->middleware('throttle:two-factor')->name('two-factor.verify');
    Route::post('/two-factor-challenge/resend', [TwoFactorChallengeController::class, 'resend'])->middleware('throttle:two-factor')->name('two-factor.resend');
});

Route::middleware('auth')->group(function (): void {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/search', AdvancedSearchController::class)->name('search.index');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/security', [SecurityController::class, 'show'])->name('security.show');
    Route::post('/security/two-factor', [SecurityController::class, 'enable'])->name('security.two-factor.enable');
    Route::delete('/security/two-factor', [SecurityController::class, 'disable'])->name('security.two-factor.disable');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/reports/export', [ReportController::class, 'export'])->name('reports.export');
    Route::get('/uyap-import', [UyapImportController::class, 'create'])->name('uyap-import.create');
    Route::post('/uyap-import', [UyapImportController::class, 'store'])->name('uyap-import.store');
    Route::resource('case-files', CaseFileController::class)->parameters(['case-files' => 'caseFile'])->except(['destroy']);
    Route::patch('/case-files/{caseFile}/status', CaseFileStatusController::class)->name('case-files.status.update');
    Route::put('/case-files/{caseFile}/assignments', CaseFileAssignmentController::class)->name('case-files.assignments.update');
    Route::post('/case-files/{caseFile}/parties', [CaseFilePartyController::class, 'store'])->name('case-files.parties.store');
    Route::delete('/case-files/{caseFile}/parties/{caseFileParty}', [CaseFilePartyController::class, 'destroy'])->name('case-files.parties.destroy');
    Route::post('/case-files/{caseFile}/documents', [CaseFileDocumentController::class, 'store'])->name('case-files.documents.store');
    Route::post('/case-files/{caseFile}/document-folders', [DocumentFolderController::class, 'store'])->name('case-files.document-folders.store');
    Route::resource('clients', ClientController::class);
    Route::get('/documents', LegalDocumentController::class)->name('legal-documents.index');
    Route::get('/documents/{document}/udf', [UdfDocumentController::class, 'show'])->name('documents.udf.show');
    Route::get('/documents/{document}/udf/edit', [UdfDocumentController::class, 'edit'])->name('documents.udf.edit');
    Route::put('/documents/{document}/udf', [UdfDocumentController::class, 'update'])->name('documents.udf.update');
    Route::get('/documents/{document}/udf/download', [UdfDocumentController::class, 'download'])->name('documents.udf.download');
    Route::post('/documents/{document}/versions', [DocumentVersionController::class, 'store'])->name('document-versions.store');
    Route::get('/document-versions/{documentVersion}/download', [DocumentVersionController::class, 'download'])->name('document-versions.download');
    Route::get('/document-versions/{documentVersion}/preview', [DocumentVersionController::class, 'preview'])->name('document-versions.preview');
    Route::resource('hearings', HearingController::class)->except(['show', 'destroy']);
    Route::resource('deadlines', DeadlineController::class)->except(['show', 'destroy']);
    Route::resource('legal-tasks', LegalTaskController::class)->parameters(['legal-tasks' => 'legalTask'])->except(['show', 'destroy']);
    Route::get('/legal-calendar', LegalCalendarController::class)->name('legal-calendar.index');
    Route::resource('service-notices', ServiceNoticeController::class)->parameters(['service-notices' => 'serviceNotice'])->except(['show', 'destroy']);
    Route::resource('mediations', MediationController::class)->except(['show', 'destroy']);
    Route::get('/financial-entries', [CaseFinancialEntryController::class, 'index'])->name('financial-entries.index');
    Route::post('/financial-entries', [CaseFinancialEntryController::class, 'store'])->name('financial-entries.store');
    Route::post('/financial-entries/{caseFinancialEntry}/reverse', [CaseFinancialEntryController::class, 'reverse'])->name('financial-entries.reverse');
    Route::resource('client-communications', ClientCommunicationController::class)->parameters(['client-communications' => 'clientCommunication'])->except(['destroy']);
    Route::get('/assignment-requests', [CaseAssignmentRequestController::class, 'index'])->name('assignment-requests.index');
    Route::post('/assignment-requests', [CaseAssignmentRequestController::class, 'store'])->name('assignment-requests.store');
    Route::post('/assignment-requests/{caseAssignmentRequest}/review', [CaseAssignmentRequestController::class, 'review'])->name('assignment-requests.review');
    Route::post('/assignment-requests/{caseAssignmentRequest}/cancel', [CaseAssignmentRequestController::class, 'cancel'])->name('assignment-requests.cancel');
    Route::get('/events/{event}/case-file/create', [EventCaseFileController::class, 'create'])->name('events.case-file.create');
    Route::post('/events/{event}/case-file', [EventCaseFileController::class, 'store'])->name('events.case-file.store');
    Route::resource('events', EventController::class);
    Route::patch('/events/{event}/status', [EventController::class, 'updateStatus'])->name('events.status.update');
    Route::patch('/events/{event}/priority', [EventController::class, 'updatePriority'])->name('events.priority.update');
    Route::patch('/events/{event}/assign-lawyer', [EventController::class, 'reassignLawyer'])->name('events.lawyer.update');
    Route::post('/events/{event}/updates', [EventUpdateController::class, 'store'])->name('events.updates.store');
    Route::post('/events/{event}/documents', [DocumentController::class, 'store'])->name('events.documents.store');
    Route::get('/documents/{document}/download', [DocumentController::class, 'download'])->name('documents.download');
    Route::delete('/documents/{document}', [DocumentController::class, 'destroy'])->name('documents.destroy');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::get('/notifications/{notification}/open', [NotificationController::class, 'open'])->name('notifications.open');
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::post('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::get('/messages', [MessageController::class, 'index'])->name('messages.index');
    Route::get('/messages/conversations/{conversation}', [MessageController::class, 'showConversation'])->name('messages.conversations.show');
    Route::post('/messages/conversations', [MessageController::class, 'storeConversation'])->name('messages.conversations.store');
    Route::post('/messages/conversations/{conversation}/messages', [MessageController::class, 'storeMessage'])->middleware('throttle:messages')->name('messages.store');
    Route::post('/messages/conversations/{conversation}/read', [MessageController::class, 'readConversation'])->name('messages.read');
    Route::get('/admin/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
    Route::get('/admin/audit-logs/{auditLog}', [AuditLogController::class, 'show'])->name('audit-logs.show');
    Route::get('/admin/users', [AdminUserController::class, 'index'])->name('admin.users.index');
    Route::get('/admin/users/create', [AdminUserController::class, 'create'])->name('admin.users.create');
    Route::post('/admin/users', [AdminUserController::class, 'store'])->name('admin.users.store');
    Route::get('/admin/users/{user}/edit', [AdminUserController::class, 'edit'])->name('admin.users.edit');
    Route::put('/admin/users/{user}', [AdminUserController::class, 'update'])->name('admin.users.update');
    Route::post('/admin/users/{user}/activate', [AdminUserController::class, 'activate'])->name('admin.users.activate');
    Route::post('/admin/users/{user}/deactivate', [AdminUserController::class, 'deactivate'])->name('admin.users.deactivate');
    Route::post('/admin/users/{user}/send-password-reset', [AdminUserController::class, 'sendPasswordReset'])->middleware('throttle:manager-password-reset')->name('admin.users.send-password-reset');
    Route::get('/admin/event-types', [AdminEventTypeController::class, 'index'])->name('admin.event-types.index');
    Route::get('/admin/event-types/create', [AdminEventTypeController::class, 'create'])->name('admin.event-types.create');
    Route::post('/admin/event-types', [AdminEventTypeController::class, 'store'])->name('admin.event-types.store');
    Route::get('/admin/event-types/{eventType}/edit', [AdminEventTypeController::class, 'edit'])->name('admin.event-types.edit');
    Route::put('/admin/event-types/{eventType}', [AdminEventTypeController::class, 'update'])->name('admin.event-types.update');
    Route::post('/admin/event-types/{eventType}/activate', [AdminEventTypeController::class, 'activate'])->name('admin.event-types.activate');
    Route::post('/admin/event-types/{eventType}/deactivate', [AdminEventTypeController::class, 'deactivate'])->name('admin.event-types.deactivate');
    Route::get('/admin/case-types', [AdminCaseTypeController::class, 'index'])->name('admin.case-types.index');
    Route::get('/admin/case-types/create', [AdminCaseTypeController::class, 'create'])->name('admin.case-types.create');
    Route::post('/admin/case-types', [AdminCaseTypeController::class, 'store'])->name('admin.case-types.store');
    Route::get('/admin/case-types/{caseType}/edit', [AdminCaseTypeController::class, 'edit'])->name('admin.case-types.edit');
    Route::put('/admin/case-types/{caseType}', [AdminCaseTypeController::class, 'update'])->name('admin.case-types.update');
    Route::post('/admin/case-types/{caseType}/activate', [AdminCaseTypeController::class, 'activate'])->name('admin.case-types.activate');
    Route::post('/admin/case-types/{caseType}/deactivate', [AdminCaseTypeController::class, 'deactivate'])->name('admin.case-types.deactivate');
});
