<x-layouts.app :title="$hearing->exists ? 'Duruşma Düzenle' : 'Yeni Duruşma'">
    <a class="text-sm font-medium text-slate-500" href="{{ route('hearings.index') }}">&larr; Duruşmalarım</a>
    <form class="mt-4 grid max-w-4xl gap-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-2" method="POST" action="{{ $hearing->exists ? route('hearings.update', $hearing) : route('hearings.store') }}">@csrf @if($hearing->exists)@method('PUT')<input type="hidden" name="lock_version" value="{{ $hearing->lock_version }}">@endif
        <div class="md:col-span-2"><h1 class="text-xl font-bold text-slate-950">{{ $hearing->exists ? 'Duruşmayı Düzenle' : 'Yeni Duruşma Oluştur' }}</h1></div>
        <div><label class="text-sm font-medium text-slate-700">Hukuki dosya</label><select name="case_file_id" required class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Seçin</option>@foreach($caseFiles as $caseFile)<option value="{{ $caseFile->id }}" @selected((string) old('case_file_id', $hearing->case_file_id) === (string) $caseFile->id)>{{ $caseFile->case_no }} · {{ $caseFile->title }}</option>@endforeach</select></div>
        <div><label class="text-sm font-medium text-slate-700">Duruşma avukatı</label><select name="lawyer_id" class="mt-1 block w-full rounded-lg border-slate-300"><option value="">Belirtilmedi</option>@foreach($lawyers as $lawyer)<option value="{{ $lawyer->id }}" @selected((string) old('lawyer_id', $hearing->lawyer_id) === (string) $lawyer->id)>{{ $lawyer->name }}</option>@endforeach</select></div>
        <div class="md:col-span-2"><label class="text-sm font-medium text-slate-700">Başlık</label><input name="title" required value="{{ old('title', $hearing->title) }}" class="mt-1 block w-full rounded-lg border-slate-300"></div>
        <div><label class="text-sm font-medium text-slate-700">Mahkeme</label><input name="court" value="{{ old('court', $hearing->court) }}" class="mt-1 block w-full rounded-lg border-slate-300"></div><div><label class="text-sm font-medium text-slate-700">Duruşma türü</label><input name="hearing_type" value="{{ old('hearing_type', $hearing->hearing_type) }}" class="mt-1 block w-full rounded-lg border-slate-300"></div>
        <div><label class="text-sm font-medium text-slate-700">Duruşma tarihi</label><input type="datetime-local" name="hearing_at" required value="{{ old('hearing_at', $hearing->hearing_at?->format('Y-m-d\TH:i')) }}" class="mt-1 block w-full rounded-lg border-slate-300"></div><div><label class="text-sm font-medium text-slate-700">Sonraki duruşma</label><input type="datetime-local" name="next_hearing_at" value="{{ old('next_hearing_at', $hearing->next_hearing_at?->format('Y-m-d\TH:i')) }}" class="mt-1 block w-full rounded-lg border-slate-300"></div>
        <div><label class="text-sm font-medium text-slate-700">Durum</label><select name="status" class="mt-1 block w-full rounded-lg border-slate-300">@foreach(App\HearingStatus::cases() as $status)<option value="{{ $status->value }}" @selected(old('status', $hearing->status?->value ?? 'scheduled') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
        <div class="md:col-span-2"><label class="text-sm font-medium text-slate-700">Açıklama</label><textarea name="description" rows="3" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('description', $hearing->description) }}</textarea></div><div class="md:col-span-2"><label class="text-sm font-medium text-slate-700">Sonuç</label><textarea name="result" rows="3" class="mt-1 block w-full rounded-lg border-slate-300">{{ old('result', $hearing->result) }}</textarea></div>
        @if($errors->any())<div class="text-sm text-red-600 md:col-span-2">{{ $errors->first() }}</div>@endif
        <div class="md:col-span-2"><button class="rounded-lg bg-indigo-700 px-5 py-2.5 text-sm font-semibold text-white">Kaydet</button></div>
    </form>
</x-layouts.app>
