<div>
    <!-- I begin to speak only when I am certain what I will say is not better left unsaid. - Cato the Younger -->
</div>
<x-layouts.app :title="$client->party->display_name">
    <div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0"><a class="text-sm font-medium text-slate-500 hover:text-slate-900" href="{{ route('clients.index') }}">&larr; Müvekkiller</a><p class="mt-4 text-xs font-semibold uppercase tracking-wider text-indigo-600">{{ $client->party->type->label() }}</p><h1 class="mt-1 break-words text-3xl font-bold text-slate-950">{{ $client->party->display_name }}</h1></div><div class="flex items-center gap-2">@can('update', $client)<a class="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm" href="{{ route('clients.edit', $client) }}">Düzenle</a>@endcan @can('delete', $client)<details class="relative"><summary class="cursor-pointer list-none rounded-lg border border-red-200 bg-white px-4 py-2 text-sm font-semibold text-red-700 shadow-sm hover:bg-red-50">Sil</summary><div class="absolute right-0 z-20 mt-2 w-72 rounded-xl border border-red-200 bg-white p-4 shadow-xl"><p class="text-sm text-slate-700">Aktif hukuki dosya ilişkisi veya iletişim geçmişi bulunan müvekkiller silinemez. Sonlanmış ilişkilerin taraf kaydı korunur.</p><form class="mt-3" method="POST" action="{{ route('clients.destroy', $client) }}">@csrf @method('DELETE')<button class="w-full rounded-lg bg-red-700 px-3 py-2 text-sm font-semibold text-white hover:bg-red-800">Silmeyi Onayla</button></form></div></details>@endcan</div></div>
    <div class="mt-6 grid gap-6 lg:grid-cols-3">
        <section class="min-w-0 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6 lg:col-span-1"><h2 class="font-semibold text-slate-900">İletişim Bilgileri</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-slate-500">Telefon</dt><dd class="mt-1 break-words font-medium text-slate-900">{{ $client->party->phone ?: '-' }}</dd></div><div><dt class="text-slate-500">E-posta</dt><dd class="mt-1 break-all font-medium text-slate-900">{{ $client->party->email ?: '-' }}</dd></div><div><dt class="text-slate-500">Adres</dt><dd class="mt-1 whitespace-pre-line break-words text-slate-700">{{ $client->party->address ?: '-' }}</dd></div>@if($canViewIdentifiers)<div><dt class="text-slate-500">Hassas Kimlik</dt><dd class="mt-1 break-all font-medium text-slate-900">@forelse($client->party->identifiers as $identifier){{ $identifier->type->label() }}: {{ $identifier->value }}@empty-@endforelse</dd></div>@endif</dl></section>
        <section class="rounded-xl border border-slate-200 bg-white shadow-sm lg:col-span-2"><div class="flex items-center justify-between border-b border-slate-100 px-6 py-4"><h2 class="font-semibold text-slate-900">Hukuki Dosyalar</h2><a class="text-sm font-medium text-indigo-600" href="{{ route('case-files.create') }}">Yeni dosya</a></div><div class="divide-y divide-slate-100">@forelse($client->party->caseFiles as $caseFile)<a class="flex items-center justify-between gap-3 px-6 py-4 hover:bg-slate-50" href="{{ route('case-files.show', $caseFile) }}"><div><p class="font-medium text-slate-900">{{ $caseFile->title }}</p><p class="mt-1 font-mono text-xs text-indigo-600">{{ $caseFile->case_no }}</p></div><span class="rounded-full px-2 py-1 text-xs font-medium {{ $caseFile->status->badgeClass() }}">{{ $caseFile->status->label() }}</span></a>@empty<p class="px-6 py-10 text-center text-sm text-slate-500">Bu müvekkile bağlı hukuki dosya bulunmuyor.</p>@endforelse</div></section>
    </div>
    <section class="mt-6 rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-4 py-4 sm:px-6"><h2 class="font-semibold">İletişim Geçmişi</h2><a class="text-sm font-medium text-indigo-600" href="{{ route('client-communications.create',['client'=>$client->id]) }}">İletişim Ekle</a></div><div class="divide-y divide-slate-100">@forelse($client->communications as $communication)<a class="block px-4 py-4 sm:px-6" href="{{ route('client-communications.show',$communication) }}"><div class="flex flex-col gap-1 sm:flex-row sm:justify-between sm:gap-3"><p class="min-w-0 break-words font-medium">{{ $communication->subject }}</p><time class="shrink-0 text-sm text-slate-500">{{ $communication->communication_at->format('d.m.Y H:i') }}</time></div><p class="mt-1 break-words text-sm text-slate-600">{{ $communication->type->label() }} · {{ $communication->user->name }}@if($communication->caseFile) · {{ $communication->caseFile->case_no }}@endif</p></a>@empty<p class="px-6 py-8 text-sm text-slate-500">İletişim kaydı bulunmuyor.</p>@endforelse</div></section>
</x-layouts.app>
