<div>
    <!-- I begin to speak only when I am certain what I will say is not better left unsaid. - Cato the Younger -->
</div>
<x-layouts.app :title="$client->party->display_name">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><a class="text-sm font-medium text-slate-500 hover:text-slate-900" href="{{ route('clients.index') }}">&larr; Müvekkiller</a><p class="mt-4 text-xs font-semibold uppercase tracking-wider text-indigo-600">{{ $client->party->type->label() }}</p><h1 class="mt-1 text-3xl font-bold text-slate-950">{{ $client->party->display_name }}</h1></div>@can('update', $client)<a class="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm" href="{{ route('clients.edit', $client) }}">Düzenle</a>@endcan</div>
    <div class="mt-6 grid gap-6 lg:grid-cols-3">
        <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-1"><h2 class="font-semibold text-slate-900">İletişim Bilgileri</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-slate-500">Telefon</dt><dd class="mt-1 font-medium text-slate-900">{{ $client->party->phone ?: '-' }}</dd></div><div><dt class="text-slate-500">E-posta</dt><dd class="mt-1 font-medium text-slate-900">{{ $client->party->email ?: '-' }}</dd></div><div><dt class="text-slate-500">Adres</dt><dd class="mt-1 whitespace-pre-line text-slate-700">{{ $client->party->address ?: '-' }}</dd></div>@if($canViewIdentifiers)<div><dt class="text-slate-500">Hassas Kimlik</dt><dd class="mt-1 font-medium text-slate-900">@forelse($client->party->identifiers as $identifier){{ $identifier->type->label() }}: {{ $identifier->value }}@empty-@endforelse</dd></div>@endif</dl></section>
        <section class="rounded-xl border border-slate-200 bg-white shadow-sm lg:col-span-2"><div class="flex items-center justify-between border-b border-slate-100 px-6 py-4"><h2 class="font-semibold text-slate-900">Hukuki Dosyalar</h2><a class="text-sm font-medium text-indigo-600" href="{{ route('case-files.create') }}">Yeni dosya</a></div><div class="divide-y divide-slate-100">@forelse($client->party->caseFiles as $caseFile)<a class="flex items-center justify-between gap-3 px-6 py-4 hover:bg-slate-50" href="{{ route('case-files.show', $caseFile) }}"><div><p class="font-medium text-slate-900">{{ $caseFile->title }}</p><p class="mt-1 font-mono text-xs text-indigo-600">{{ $caseFile->case_no }}</p></div><span class="rounded-full px-2 py-1 text-xs font-medium {{ $caseFile->status->badgeClass() }}">{{ $caseFile->status->label() }}</span></a>@empty<p class="px-6 py-10 text-center text-sm text-slate-500">Bu müvekkile bağlı hukuki dosya bulunmuyor.</p>@endforelse</div></section>
    </div>
    <section class="mt-6 rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-6 py-4"><h2 class="font-semibold">İletişim Geçmişi</h2><a class="text-sm font-medium text-indigo-600" href="{{ route('client-communications.create',['client'=>$client->id]) }}">İletişim Ekle</a></div><div class="divide-y divide-slate-100">@forelse($client->communications as $communication)<a class="block px-6 py-4" href="{{ route('client-communications.show',$communication) }}"><div class="flex justify-between gap-3"><p class="font-medium">{{ $communication->subject }}</p><time class="text-sm text-slate-500">{{ $communication->communication_at->format('d.m.Y H:i') }}</time></div><p class="mt-1 text-sm text-slate-600">{{ $communication->type->label() }} · {{ $communication->user->name }}@if($communication->caseFile) · {{ $communication->caseFile->case_no }}@endif</p></a>@empty<p class="px-6 py-8 text-sm text-slate-500">İletişim kaydı bulunmuyor.</p>@endforelse</div></section>
</x-layouts.app>
