<?php

namespace App;

enum AuditAction: string
{
    case UserLogin = 'USER_LOGIN';
    case UserLoginFailed = 'USER_LOGIN_FAILED';
    case UserLogout = 'USER_LOGOUT';
    case EventCreated = 'EVENT_CREATED';
    case EventViewed = 'EVENT_VIEWED';
    case EventUpdated = 'EVENT_UPDATED';
    case EventDeleted = 'EVENT_DELETED';
    case EventStatusChanged = 'EVENT_STATUS_CHANGED';
    case EventClosed = 'EVENT_CLOSED';
    case EventPriorityChanged = 'EVENT_PRIORITY_CHANGED';
    case EventReassigned = 'EVENT_REASSIGNED';
    case EventUpdateCreated = 'EVENT_UPDATE_CREATED';
    case DocumentUploaded = 'DOCUMENT_UPLOADED';
    case DocumentDownloaded = 'DOCUMENT_DOWNLOADED';
    case DocumentDeleted = 'DOCUMENT_DELETED';
    case DocumentFolderCreated = 'DOCUMENT_FOLDER_CREATED';
    case DocumentVersionUploaded = 'DOCUMENT_VERSION_UPLOADED';
    case UdfViewed = 'UDF_VIEWED';
    case UdfEditStarted = 'UDF_EDIT_STARTED';
    case UdfVersionCreated = 'UDF_VERSION_CREATED';
    case UdfDownloaded = 'UDF_DOWNLOADED';
    case UdfParseFailed = 'UDF_PARSE_FAILED';
    case HearingCreated = 'HEARING_CREATED';
    case HearingUpdated = 'HEARING_UPDATED';
    case DeadlineCreated = 'DEADLINE_CREATED';
    case DeadlineUpdated = 'DEADLINE_UPDATED';
    case LegalTaskCreated = 'LEGAL_TASK_CREATED';
    case LegalTaskUpdated = 'LEGAL_TASK_UPDATED';
    case ServiceNoticeCreated = 'SERVICE_NOTICE_CREATED';
    case ServiceNoticeUpdated = 'SERVICE_NOTICE_UPDATED';
    case MediationCreated = 'MEDIATION_CREATED';
    case MediationUpdated = 'MEDIATION_UPDATED';
    case FinancialEntryCreated = 'FINANCIAL_ENTRY_CREATED';
    case FinancialEntryReversed = 'FINANCIAL_ENTRY_REVERSED';
    case ClientCommunicationCreated = 'CLIENT_COMMUNICATION_CREATED';
    case ClientCommunicationUpdated = 'CLIENT_COMMUNICATION_UPDATED';
    case CaseAssignmentRequested = 'CASE_ASSIGNMENT_REQUESTED';
    case CaseAssignmentRequestApproved = 'CASE_ASSIGNMENT_REQUEST_APPROVED';
    case CaseAssignmentRequestRejected = 'CASE_ASSIGNMENT_REQUEST_REJECTED';
    case CaseAssignmentRequestCancelled = 'CASE_ASSIGNMENT_REQUEST_CANCELLED';
    case UserCreated = 'USER_CREATED';
    case UserUpdated = 'USER_UPDATED';
    case UserActivated = 'USER_ACTIVATED';
    case UserDeactivated = 'USER_DEACTIVATED';
    case UserRoleChanged = 'USER_ROLE_CHANGED';
    case EventTypeCreated = 'EVENT_TYPE_CREATED';
    case EventTypeUpdated = 'EVENT_TYPE_UPDATED';
    case EventTypeActivated = 'EVENT_TYPE_ACTIVATED';
    case EventTypeDeactivated = 'EVENT_TYPE_DEACTIVATED';
    case CaseTypeCreated = 'CASE_TYPE_CREATED';
    case CaseTypeUpdated = 'CASE_TYPE_UPDATED';
    case CaseTypeActivated = 'CASE_TYPE_ACTIVATED';
    case CaseTypeDeactivated = 'CASE_TYPE_DEACTIVATED';
    case CaseFileCreated = 'CASE_FILE_CREATED';
    case CaseFileUpdated = 'CASE_FILE_UPDATED';
    case CaseFileViewed = 'CASE_FILE_VIEWED';
    case CaseFileStatusChanged = 'CASE_FILE_STATUS_CHANGED';
    case CaseFileAssignmentsChanged = 'CASE_FILE_ASSIGNMENTS_CHANGED';
    case CaseFileEventLinked = 'CASE_FILE_EVENT_LINKED';
    case CaseFilePartyAdded = 'CASE_FILE_PARTY_ADDED';
    case CaseFilePartyRemoved = 'CASE_FILE_PARTY_REMOVED';
    case ClientCreated = 'CLIENT_CREATED';
    case ClientUpdated = 'CLIENT_UPDATED';
    case ClientDeleted = 'CLIENT_DELETED';
    case PasswordResetRequested = 'PASSWORD_RESET_REQUESTED';
    case PasswordResetCompleted = 'PASSWORD_RESET_COMPLETED';
    case TwoFactorEnabled = 'TWO_FACTOR_ENABLED';
    case TwoFactorDisabled = 'TWO_FACTOR_DISABLED';
    case UyapCaseImported = 'UYAP_CASE_IMPORTED';
}
